// Costa Rica
// Belinda Brown, belindabrownr04@gmail.com
// July, 2021
//                  
//        Calculate the average per 
// category using the measure in Power bi

// Table name with '' 
// Inside [] as header name 

Average = 
CALCULATE (
    AVERAGE ( 'Table (2)'[Value] ),
    FILTER ( ALLSELECTED ( 'Table (2)' ), 'Table (2)'[Category ] = MAX ( 'Table (2)'[Category ] ) )
)


AverageMeasure =
CALCULATE ( AVERAGE ( 'Table (2)'[Value] ), ALLEXCEPT ( Table (2), 'Table (2)'[Category ]  ) )


// References 
// [1] https://www.enjoysharepoint.com/power-bi-measure-by-category/
// [2] https://blog.enterprisedna.co/calculating-averages-per-day-month-or-year-within-power-bi/
// [3] https://www.sqlbi.com/tv/average-averagea-averagex-dax-guide/
// [4] https://docs.microsoft.com/en-us/power-bi/create-reports/service-aggregates
