// Costa Rica
// Belinda Brown, belindabrownr04@gmail.com
// July, 2020
//                  Calculate days Between Periods 
//                  with filter 

#daysBetweenPeriods = 
VAR daysBetweenPeriods =
    CALCULATE (
        LASTDATE ( ObjectClosedDate[ClosedDate] ),
        FILTER (
            ALLEXCEPT ( ObjectClosedDate, ObjectClosedDate[Type] ),
            ObjectClosedDate[ClosedDate] < EARLIER ( ObjectClosedDate[ClosedDate]  )
        )
    )
RETURN
    DATEDIFF ( daysBetweenPeriods, ObjectClosedDate[ClosedDate] , DAY )